services:
  adminer:
    image: adminer
    ports:
      - 8888:8080
    networks:
      - spring-cloud-network  
  db:
    image: postgres
    container_name: db
    environment:
      - POSTGRES_USER=compose-postgres
      - POSTGRES_PASSWORD=compose-postgres
    networks:
      - spring-cloud-network   
    volumes:
      - ./postgres-data:/var/lib/postgresql/data  
  backend:
    image: backend:latest
    build:
      context: .
    container_name: app
    depends_on:
      - db
    ports:
      - 8080:8080
    networks:
      - spring-cloud-network    
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/compose-postgres
      - SPRING_DATASOURCE_USERNAME=compose-postgres
      - SPRING_DATASOURCE_PASSWORD=compose-postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
networks:
    spring-cloud-network:
        driver: bridge